"""Hevy API models. Domain sub-modules append their re-exports below."""

from hevy.models.common import HevyAPIError, OperationStatus, RepRange, SetType

# domain re-exports
from hevy.models.exercises import (
    CreateCustomExerciseRequestExercise,
    CreateExerciseTemplateResponse,
    CustomExerciseType,
    EquipmentCategory,
    ExerciseHistoryEntry,
    ExerciseHistoryResponse,
    ExerciseTemplate,
    MuscleGroup,
    PaginatedExerciseTemplates,
    PaginatedRoutineFolders,
    PostRoutineFolderRequestFolder,
    RoutineFolder,
)
from hevy.models.measurements import (
    BodyMeasurement,
    PaginatedBodyMeasurements,
    PutBodyMeasurement,
)
from hevy.models.routines import (
    PaginatedRoutines,
    PostRoutinesRequestExercise,
    PostRoutinesRequestRoutine,
    PostRoutinesRequestSet,
    PutRoutinesRequestExercise,
    PutRoutinesRequestRoutine,
    PutRoutinesRequestSet,
    Routine,
    RoutineExercise,
    RoutineExerciseSet,
)
from hevy.models.user import UserInfo, UserInfoResponse
from hevy.models.workouts import (
    DeletedWorkout,
    Exercise,
    PaginatedWorkoutEvents,
    PaginatedWorkouts,
    PostWorkoutsRequestExercise,
    PostWorkoutsRequestSet,
    PostWorkoutsRequestWorkout,
    Set,
    Workout,
    WorkoutCount,
)

__all__ = [
    "BodyMeasurement",
    "CreateCustomExerciseRequestExercise",
    "CreateExerciseTemplateResponse",
    "CustomExerciseType",
    "DeletedWorkout",
    "EquipmentCategory",
    "Exercise",
    "ExerciseHistoryEntry",
    "ExerciseHistoryResponse",
    "ExerciseTemplate",
    "HevyAPIError",
    "MuscleGroup",
    "OperationStatus",
    "PaginatedBodyMeasurements",
    "PaginatedExerciseTemplates",
    "PaginatedRoutineFolders",
    "PaginatedRoutines",
    "PaginatedWorkoutEvents",
    "PaginatedWorkouts",
    "PostRoutineFolderRequestFolder",
    "PostRoutinesRequestExercise",
    "PostRoutinesRequestRoutine",
    "PostRoutinesRequestSet",
    "PostWorkoutsRequestExercise",
    "PostWorkoutsRequestSet",
    "PostWorkoutsRequestWorkout",
    "PutBodyMeasurement",
    "PutRoutinesRequestExercise",
    "PutRoutinesRequestRoutine",
    "PutRoutinesRequestSet",
    "RepRange",
    "Routine",
    "RoutineExercise",
    "RoutineExerciseSet",
    "RoutineFolder",
    "Set",
    "SetType",
    "UserInfo",
    "UserInfoResponse",
    "Workout",
    "WorkoutCount",
]
